### ISSUE TITLE
api: cache local user (infra providerID) in a somewhat permanent manner

### ISSUE THREAD

**Issue by kimskimchi** [infrahq/infra#1380]
Currently, there is no way to determine what the providerID is when logging in a user as local user.
The only way to retrieve this providerID is to call `listProviders`, and locally save the information.

So currently:
1. we call `listProviders`
2. we find the local login provider (aka 'infra provider'), which has a providerID
3. we save it in memory (variable), and/or/then save it to the local configuration 
4. backend doesn't really need it, so we only really save it for local use cases. 
    
Code for login/logout should not rely on a variable retain this providerID - there should be a source of truth for it when calling the api. 

At the minimum, either `loginRequest` or `loginResponse` should have the providerID.

**Comment by pdevine** [comment]
Closing for now.
