### ISSUE TITLE
Refactor client to not be so modifiable within package `cmd`

### ISSUE THREAD

**Issue by kimskimchi** [infrahq/infra#1400]
Current we pass in someFunctionToCallAPI(client, ...)

We should be discouraging the modification of the client, since it really shouldn't be touched anywhere except when the state of config changes (eg. login, logout, ...)

We can have a client.go , and set a var there of that client, for lazy initialization.

**Comment by ssoroka** [comment]
not sure I understand what this issue is trying to say.

**Comment by dnephin** [comment]
Ya, using a package-level variable is probably not what we want.

A great way to indicate that a function doesn't modify something, without switching to using the struct value, is to accept an interface. For example:

```go
type usersClient interface {
    ListUsers(req ListUsersRequest) (*ListResponse[User], error)
    ...
}

func someFunctionToCallAPI(client usersClient) error {
    ...
}
```

`api.Client` already implements` usersClient`. This way the function declares that it's only going to use a few methods, and the reader can pretty quickly see that the methods are likely not going to modify anything in the client.
