### ISSUE TITLE
Add a way to format the output from the output of infra CLI commands

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#1419]
## Is your feature request related to a problem? Please describe.
In order to easily parse the output of the `infra info` command it would be nice to have some way for it to format the fields I want (ex: with a flag).

## Describe the solution you'd like
Maybe something like:
```
$ infra info --json
{
  "user": "example@example.com",
  "server": "localhost"
}
```

**Comment by jmorganca** [comment]
Closing for #972
