### ISSUE TITLE
api: prevent the creation of identities that use a reserved name

### ISSUE THREAD

**Issue by dnephin** [infrahq/infra#1445]
Partially related to #1425, but I think this might be valuable for other reasons as well.

I propose we do not allow anyone to create an identity with the following names:

* `connector`
* `system`
* `infra`
* `self`
* others?

Reserving these terms would allow us to use them for other purposes in the future, and prevents a possibly confusing scenario where an identity has a name that could convey the wrong meaning.

**Comment by dnephin** [comment]
I guess this is not an issue because the API uses `id` for queries and does not have any control over IDs. In the future if any API endpoints accepts `name` we will want to do this.

**Comment by ssoroka** [comment]
sounds like we should do this for machine identities. 

fyi: users are allowed to set the ID field. This is common in systems that support uuids so that the client can generate a bunch of ids and not have to wait until creation to know what the assigned ID will be.
