### ISSUE TITLE
server.config: secerts and keys can not be loaded from config files

### ISSUE THREAD

**Issue by dnephin** [infrahq/infra#1519]
## Describe the bug

Secrets and keys can be added to the server config file, but loading those values does not work. It results in an error about an unexpected type.  Config loading for those types depended on a custom `UnmarshalYAML` method. When we switched from YAML decoding to viper (which uses mapstructure) those methods are no longer called because config is first loaded from yaml into a `map[string]interface{}`. The yaml decoder has no knowledge of these custom `UnmarshalYAML`.  Then mapstructure is used to convert from `map[string]interface{}` to the appropriate type, but it doesn't know how to use the `UnmarshalYAML` method.

## Expected behavior

Adding secrets and keys to a config file works.

## Additional context

We can fix this by adding a decode hook and changing the `UnmarshalYAML` methods to implement something the decode hook can use.

**Comment by jmorganca** [comment]
Resolved in #1600 and #1520 (thanks @dnephin !)
