### ISSUE TITLE
Show the identity name in the list of servers when running `infra login`

### ISSUE THREAD

**Issue by dnephin** [infrahq/infra#1539]
## Is your feature request related to a problem? Please describe.

A user may have multiple logins to a single infra server. This is often true for admins who may have one very privileged identity (the `admin` machine identity), and another one for less privileged operations.

Currently `infra login` only shows the list of servers, but doesn't show the identity associated with the server.

## Describe the solution you'd like

I'd like to see the identity (i believe that is stored as `ClientHostConfig.Name`), and maybe also the expiry time and `current`, as part of the list of servers. Something roughly like this

```
$ infra login
? Selet a server: [...]
  localhost:8080 as myusername@example.com (expired 2days ago)
  localhost:8080 as admin (active, expires in 10 hours) 
  dev.myorg.net:8080 as myusername@example.com (expires in 2 hours)
```

**Comment by j-sneh** [comment]
Is this still relevant with the move to SaaS?

**Comment by dnephin** [comment]
Could still be relevant if org admins use a separate admin account from their regular user account. Not sure how common that will be.

**Comment by dnephin** [comment]
I think this may still be relevant. Admins may have multiple accounts per organization. Let's keep this around for a bit longer.
