### ISSUE TITLE
cmd/login: print any active session before prompting for a server

### ISSUE THREAD

**Issue by dnephin** [infrahq/infra#1540]
## Is your feature request related to a problem? Please describe.

`infra info` prints information about the current session (I think), but a user may not always know to go there first.  It can be helpful to tell the user about their active session before prompting for login.

## Describe the solution you'd like

I imagine this could look something like this for a session that is active and not expired:

```
$ infra login

You are logged into localhost:8080 as myusername@example.com. This session expires in 2 hours.

To login as a different user or to a different server select a server below.
? Select a server: ...
> ...
```

**Comment by pdevine** [comment]
Going to close this for now. We'll revisit w/ #1820 and #1857
