### ISSUE TITLE
Prometheus telemetry for Server & Connector

### ISSUE THREAD

**Issue by dkulchinsky** [infrahq/infra#1580]
## Is your feature request related to a problem? Please describe.

I think it would be very valuable to expose various telemetry using Prometheus exposition in both Infra & Engine, tracking various aspects of of the system to monitor overall health, sessions, failures, etc..

## Describe the solution you'd like

Infra & Engine should provide a `/metrics` endpoint where prometheus format metrics can be scraped

## Describe alternatives you've considered

Considering the wide adoption of prometheus, especially in the kubernetes eco-system, I think this makes the most sense.

a sidecar approach would work as well, if telemetry is going to be exposed in a different metrics format and could be translated by the sidecar to prometheus metrics format, but that seems to be like an unnecessary overhead.

## Environment Details

0.10.1

1.21.9

GKE, kops, Kubesrpay

**Comment by mxyng** [comment]
Closing since metrics has already been implemented for both the server and connector
