### ISSUE TITLE
Publish binaries to GitHub releases

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#1582]
We should publish raw `arm64` and `amd64` binaries for:
* Windows
* Linux
* Mac

Related:
* #899

**Comment by dnephin** [comment]
https://github.com/infrahq/infra/releases

This looks good. The only one we don't have is `windows_arm64`. I'm not sure if we need that. If not we can close this.

**Comment by jmorganca** [comment]
Great! No need for now. Closing
