### ISSUE TITLE
Generate metrics docs from prometheus registry

### ISSUE THREAD

**Issue by mxyng** [infrahq/infra#1589]
## Is your feature request related to a problem? Please describe.

Metrics is hidden behind a running server/connector and may change significantly over the course of the product. A simple way of keeping docs up to date is to generate it from the code. 

## Describe the solution you'd like

As part of `make docs`, gather Prometheus metrics from the server and connector and template out the metric and description into a markdown file.

## Describe alternatives you've considered

A future enhancement is to export the metrics after an integration test and use those contents instead. Not only will this give use metric and description, but it can also give an example of what values or labels to expect.

**Comment by dnephin** [comment]
https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#Registry.Gather seems like it should make it easy to get all the metrics registered to a particular `Registry`, mostly we just need a way of rendering each as markdown.
