### ISSUE TITLE
CLI list ordering 

### ISSUE THREAD

**Issue by mchiang0610** [infrahq/infra#1606]
Current: 
<img width="454" alt="image" src="https://user-images.githubusercontent.com/3325447/163076675-126dec32-bb1c-4897-a1f7-4588b89b4aef.png">

Expected: 
- Alphabetical ordering

**Comment by technovangelist** [comment]
To be clear, the current ordering is consistent but not based on order of creation, order of last login, or any other order I can think of.

**Comment by jmorganca** [comment]
closing for #1341
