### ISSUE TITLE
Sort order in infra list is simple alphabetical

### ISSUE THREAD

**Issue by technovangelist** [infrahq/infra#1636]
## Describe the bug

When I run `infra list` the sort order is a simple alphabetical list. Which doesn't take into account the clusters listed. 
<img width="406" alt="CleanShot 2022-04-15 at 11 17 06@2x" src="https://user-images.githubusercontent.com/633681/163606423-4a1ef275-e8c7-4868-9b48-e763f495667a.png">

## Expected behavior

I would have expected the two kubernetes.marketing resources to be listed together.

## Environment

Infra: 0.10.3
k8s client: 1.22.5
k8s server: 1.22.8
server on DO

**Comment by jmorganca** [comment]
closing for #1341
