### ISSUE TITLE
Avoid use of SNI

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#1637]
Many Kubernetes clients don't have great SNI support (e.g. javascript-based ones)

We should generate a CA with the connectors and generate self-signed certs from that CA with the proper SAN fields instead of relying on SNI since many clients don't have this.

Potentially helpful: https://helm.sh/docs/chart_template_guide/function_list/#genca

**Comment by ssoroka** [comment]
CN is deprecated, the replacement is SAN. Not sure how SNI plays into this. What's the original problem you're trying to address?

**Comment by jmorganca** [comment]
SAN indeed – the issue here is that we are using SNI and many official Kubernetes clients don't support this TLS feature

**Comment by ssoroka** [comment]
sounds like adding SAN will fix the problem. how did SNI serve up the certificate name before? i thought that was a client-side thing
