### ISSUE TITLE
UI: grant modal input should reset to "view" after sharing with a user

### ISSUE THREAD

**Issue by hoyyeva** [infrahq/infra#1683]
The dropdown on the input component doesn't reset back to `view` after clicking share

Steps to reproduce:
1. click on one of the clusters, the grant modal shows up
2. type an email and select `edit` or `admin` and hit share
3. the email and the grant role is created
4. the dropdown on the input component doesn't reset back to the initial value `view`

Expected behaviour
the dropdown should set it back to the initial value `view`

**Comment by jmorganca** [comment]
This was fixed in `main`
