### ISSUE TITLE
Add a cental mock/stub API for CLI testing

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#1716]
## Is your feature request related to a problem? Please describe.
When writing CLI tests we have been creating stub API endpoints as needed. This works, but it adds a lot of repetition to our tests that doesn't add a lot of value as far as testing the CLI specifically. 

## Describe the solution you'd like
We should add a central API stub for CLI tests that can be re-used.

## Describe alternatives you've considered
> One option is to run a full server.Server, which removes the need to return canned data, but introduces the need to create the entities in the DB. I'm not sure how much extra time that will add to tests, but it's an option we can try out. That approach would also makes it much harder to write these tests, because we can't predict the IDs or times in the API responses.

> If our API handlers accepted an interface for the "backend" (what is currently access and data) we could run a real API router, with a fake backend to inject the data. That might be less work than what we have here. That would be a much larger change, and probably not something we can easily do just for this purpose.

> Another option would be to extract some of this, and make a more complete "fake" API. We could use an actual router that simulates our real API and put that in a more central place. That might allow us to remove some of the boilerplate path matching and JSON encoding, and allow these setup methods to only specify canned responses for specific inputs.

## Additional context
No functional change, just for tests.

**Comment by dnephin** [comment]
#2098 introduces a way to test the CLI with a real API server that we run in process. Our `api.Client` is pretty nice and makes it relatively easy to create things. If this approach continues to work well then maybe we won't need a central fake. We can use a real server to test the CLI.

At this time, starting the server takes about 30 milliseconds, and that server can be shared by many subtests. So our tests are still quite fast , and are more realistic than a fake. 

There may still be some cases where we want to test against a fake, but for those the per-test fakes might work out fine.

Let's keep this issue open for a bit longer to see how well things work with the real API server.

**Comment by dnephin** [comment]
The approach we introduced in #2098 seems to be working well. We have a number of tests using it and they run reasonable fast. I'm going to close this for now, but let's re-open if we once again have a need for more complex fakes for the server API.
