### ISSUE TITLE
cli: do not print colors if in non-interactive

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#1719]
In non-interactive environments infra shouldn't print color codes.

Example:

```
Command failed: /opt/homebrew/bin/infra tokens add [31mERROR[0m Session expired. Run 'infra login' to start a new session.
```

**Comment by dnephin** [comment]
Oh ya, this is definitely a problem. I'm used to other logging libraries which auto-detect color for you. Apparently zap does not. This should be an easy thing to fix.
