### ISSUE TITLE
api: `POST /api/grants` should validate subject/role/resource exists and error if they do not

### ISSUE THREAD

**Issue by mxyng** [infrahq/infra#1723]
If a grant is created for a subject/role/resource that does not exist, it has no effect and does not serve any purpose. Therefore it should error and warn the caller of nonexistent references. The user will need to create the missing resources or recreate the grant with a force flag.

Grants from config should are not affected

**Comment by pdevine** [comment]
This is important in the CLI, but it's not as important in the API. I'm going to close this for now.
