### ISSUE TITLE
Identity groups should be cleaned up if the identity provider hasn't been synced in a certain amount of time

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#1726]
## Describe the bug
When an identity's groups are updated they are set based on the provider that was used to authenticate with Infra. If multiple external identity providers are being used this means that groups from a provider not used to authenticate will stick around until the identity provider is used again.

## Expected behavior
Identity groups from a provider that hasn't been used to authenticate in a while should be removed from the identity after a length of time, maybe 30 days.

## Relevant Infra Logs
```
$ infra login localhost
? Select a login method: okta-1 (dev-1.okta.com)
  Logging in with okta...
  Logged in as bruce@example.com

$ infra info           

            Server: localhost
          Identity: bruce@example.com (6DuKwL6uVa)
 Identity Provider: okta-1(dev-1.okta.com)
            Groups: Everyone, developers

# sign in again using a different Okta in which I am not a member of the developers group

$ infra login localhost
? Select a login method: okta-2 (dev-2.okta.com)
  Logging in with okta...
  Logged in as bruce@example.com

$ infra info           

            Server: localhost
          Identity: bruce@example.com (6DuKwL6uVa)
 Identity Provider: okta-2 (dev-2.okta.com)
            Groups: Everyone, developers # this still matches the groups in okta-1, but was not checked
```

**Comment by ssoroka** [comment]
Pending discussion, I think this is working as intended.

**Comment by BruceMacD** [comment]
Closing for now as won't do, this can be manually modified in Infra.
