### ISSUE TITLE
UI: login with safari gets local error

### ISSUE THREAD

**Issue by technovangelist** [infrahq/infra#1762]
## Describe the bug
![CleanShot 2022-04-28 at 10 22 27](https://user-images.githubusercontent.com/633681/165811404-cac7097b-8389-4f1b-ad4d-2cb6eded9eec.png)

tried logging in with chrome and no issue, using safari and i get  local error

## Expected behavior
safari should work the same as chrome

## Screenshots
see above

## Environment
0.12.1 server and client, MacBook pro m1 max, macOS 12.3

```
$ infra version
```

```
$ kubectl version
```
kubectl version, client and server 1.22.5

docker desktop

**Comment by dnephin** [comment]
I see similar things with Chrome on Linux. Before logging in, I see 401 errors in the console log
