### ISSUE TITLE
ui: login with user via cli does not work well with ui

### ISSUE THREAD

**Issue by hoyyeva** [infrahq/infra#1774]
scenario 1 
Logging in with a user created with infra id add fails with Invalid credentials. After some time, the UI updates as if I logged in successfully. No password change screen is displayed. 

scenario 2
I created a local user with the CLI. Then I tried to login as a local user in the UI.  The UI said “Invalid credentials”, but when I reload the page I’m logged in as that user. It was a one-time-password, so trying to use that password again failed.  
Login with a regular local user that had reset their password did work.

both scenarios seem similar might be table to resolve the same fix, worth to investigate together

**Comment by BruceMacD** [comment]
Not reproducible as of 0.13.0
