### ISSUE TITLE
ui: admin panel seems cut off on safari

### ISSUE THREAD

**Issue by hoyyeva** [infrahq/infra#1781]
<img width="217" alt="Untitled" src="https://user-images.githubusercontent.com/63033505/165868224-0acecef2-a9c1-4260-b29c-fa8e1deddfe0.png">

**Comment by kimskimchi** [comment]
note: this happens when there is a browser popup (safari, haven't tested others yet)

**Comment by jmorganca** [comment]
This was fixed on `main`
