### ISSUE TITLE
Return per-field errors in API

### ISSUE THREAD

**Issue by hoyyeva** [infrahq/infra#1783]
<img width="464" alt="Untitled" src="https://user-images.githubusercontent.com/63033505/165868419-62f1c5df-4da1-475f-b5af-a778b2a83903.png">

**Comment by hoyyeva** [comment]
this might need to fix from the server side. The client is displaying the error message that is coming from the server side.

**Comment by pdevine** [comment]
Depends on #1686

**Comment by pdevine** [comment]
Also #1763

**Comment by kimskimchi** [comment]
Will sync with @dnephin & write a design doc, then once changes are in, consume messages from UI/CLI (sync with @hoyyeva needed here).

**Comment by kimskimchi** [comment]
Validation errors are now returned. 400s will be returned with ValidationError, which will have a map of field names and its errors. 

See example in https://github.com/infrahq/infra/pull/2651, `users.go`
