### ISSUE TITLE
cli: `infra logout` doesn't clear the kubeconfig context

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#1855]
```
$ infra logout
Logged out of server localhost

$ kubectl config get-contexts
CURRENT   NAME             CLUSTER          AUTHINFO         NAMESPACE
          docker-desktop   docker-desktop   docker-desktop

$ kubectl get pods
Error in configuration: context was not found for specified context: infra:local-cluster
```

I would expect that the default context would be cleared

**Comment by kimskimchi** [comment]
Few points that were brought up on this idea: 
- this will mean that logout will change context behind the scenes. Logging in means infra knows what context user wants, but for logout, infra does not know what context user expects.
- file will need to have 'current' flag put in and modify `kubernetes.go`'s  current context 
- infra will need to determine what context we should set it back to. this requires discussion - 'how do we determine the default'?
