### ISSUE TITLE
api: remove polymorphic IDs

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#1859]
Polymorphic IDs is a micro-format which is difficult for users to understand, parse and serialize.

**Comment by ssoroka** [comment]
are you proposing to use email and group name for grant subjects?

**Comment by dnephin** [comment]
We only use Polymorphic IDs in grants, right? In all other cases we can use a `uid.ID` directly.

I think the underlying problem is that we need to identify the kind of subject. So we could do that entirely in the grants api type and model using a structured representation.

```go
type Grant struct {
    Subject GrantSubject
    ...
}

// GrantSubject is a union type of user or group. Only one of User or Group may be set,
// it is an error to specify a non-zero 0 for both.
type GrantSubject struct {
    User uid.ID
    Group uid.ID
}
```

Alternatively:

```go
type GrantSubject struct {
    ID uid.ID
    Kind string // user or group
}
```

**Comment by mxyng** [comment]
I think an alternative is to simply dereference the polymorphic ID in the API server and return either `User` or `Group` as IDs instead of the polymorphic ID stored in the DB
