### ISSUE TITLE
docs: infra server configuration isn't documented anywhere

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#1890]
## Page URL
https://github.com/infrahq/infra/tree/main/docs/install/configure

## Describe the Issue
Only configuration of secrets, encryption, domains, and postgres is documented. There is no explanation of the Infra server state configuration.

## Suggested Solution
Add a document explaining this Infra server config and how to apply it:
```
server:
  config:
    version: 0.2
    providers:
      ...
    grants:
      ...
    users:
      ...
```

**Comment by dnephin** [comment]
We don't necessarily need to do this immediately, but I was hoping that now that we have `internal/cmd/cliopts` for config parsing, we could add a docs generator to that same package. That would mirror how we document our CLi and API (both have markdown generators based on the Go source).
