### ISSUE TITLE
"infra grants add" with no args should show help

### ISSUE THREAD

**Issue by ssoroka** [infrahq/infra#1912]

**Comment by kimskimchi** [comment]
this was defined in #1674, it shows a short form of help. Assigning to @dnephin

**Comment by dnephin** [comment]
Original issue for this #1551

Seems like this works well today. We could show the full help, but often the help text is long enough that showing all the help hides the error message and can be more confusing to the user. 

Showing just usage is a nice balance of explaining the are order, and giving the user the command to learn more.

What's the motivation for changing it, and is it only a problem with `grants add`, or all commands? Everything should be working the same way today.
