### ISSUE TITLE
docs: no backslash commands

### ISSUE THREAD

**Issue by ssoroka** [infrahq/infra#1962]
backslashes in the quickstart guide can be error prone.

```
helm upgrade --install infra-connector infrahq/infra \
  --set connector.config.name=example-cluster \
  --set connector.config.server=<INFRA_SERVER_HOSTNAME> \
  --set connector.config.accessKey=<ACCESS_KEY> \
  --set connector.config.skipTLSVerify=true
```
the suggestion was made to change these to environment variables and have a wrapping line in the docs

**Comment by j-sneh** [comment]
Environment variable syntax varies between Windows and Unix shells. Should we add both? I can't test on windows command prompt.

**Comment by ssoroka** [comment]
Good question. I wonder if backslashes even work there. If you have something ready I can test it on Windows for you.

**Comment by dnephin** [comment]
Another option to fix this would be to have our CLI output the values to helm. 

Looking at the setting:
* `name` is optional but could be specified by the user
* `server` is know to the CLI (can be looked up in the client host config)
* `accessKey` can be either created or looked up by the CLI (using the API)
* `skipTLSVerify` will be replaced by a flag to trust the CA. This can also be looked up by the CLI in the client host config.


There are a few different ways we could have the CLI provide these options to help:
1. generate a `values.yaml` file and pass it to helm (@mxyng suggested this in slack a few days ago)
   ```
   infra connector helm-values --name example-cluster | helm -f- upgrade --install infra-connector infrahq/infra
   ```
   or with some customizations in a values.yaml
   ```
   infra connector helm-values -f values.yaml | helm -f- upgrade --install infra-connector infrahq/infra
   ```
2. Or we could generate  the `values.yaml` and also run helm
    ```
    infra connector deploy --name example-cluster
    ```
    This command could have command line flags to set the name of the repo (`infrahq/infra`) and allow other flags
    to be passed to `helm` (ex: `--install`, `--devel`, `--dry-run`). This approach would also allow us to optional prompt the user to confirm the infra server and kubernetes hostname are the ones they expect to use.

**Comment by technovangelist** [comment]
the suggestion is to change something that is easy to read and requires them to update the command according to their usecase, to something that may not work at all depending on their shell and OS. We should keep it simple which it already is.
