### ISSUE TITLE
api: use standard model ID to look up access key

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#1992]
## Describe the bug
Currently we use a "key ID" field to look up access keys in the database. This is left over from an earlier time when our database IDs weren't as friendly as they are now (they used to be long random strings, but the snowflake format is nicer).

## Expected behavior
Use the model.ID we have on all of our database models to look up access keys.

## Additional context
The expected length of the current access key ID is probably not the same as the snowflake iD, migrations will need to be accounted for.

**Comment by ssoroka** [comment]
This makes keys somewhat guessable, but that's probably not a problem since there's also a key secret involved.

**Comment by dnephin** [comment]
Another option would be to change the KeyID to the primary key, and remove the `id` column. Or even rename the `keyID` column to `id`.  That might make the migration easier by allowing us to keep the same values for access keys, but it does make access keys a special case.

**Comment by dnephin** [comment]
Another option would be to change the KeyID to the primary key, and remove the `id` column. Or even rename the `keyID` column to `id`.  That might make the migration easier by allowing us to keep the same values for access keys, but it does make access keys a special case.
