### ISSUE TITLE
api: server should custom-format all known error messages

### ISSUE THREAD

**Issue by ssoroka** [infrahq/infra#2008]
control error formatting from server side. eg sendAPIError detects `internal.ErrDuplicate`, but rather than sending back a nice formatted error including the offending field, we send back the raw error as the message, which results in a less than optimal client experience.

suggestion:
internal errors should define a human-formatted (end-user-formatted?) component to them that the API can respond with instead.

**Comment by ssoroka** [comment]
related to https://github.com/infrahq/infra/issues/1686

**Comment by jmorganca** [comment]
Closing for #1686 since it's being worked on - and linking since there's great suggestions here.
