### ISSUE TITLE
enforce password requirements on server

### ISSUE THREAD

**Issue by yeshwanth1312** [infrahq/infra#2024]
## Is your feature request related to a problem? Please describe.

We would like to enforcece password requirements when users are changing their password for the first time 

## Describe the solution you'd like

We would like to see an option for having caps, special character,s and minimum password length (which is 8 now, We would like to have something configurable )

## Environment Details

```
$ infra version
```

```
$ kubectl version
```

**Comment by kimskimchi** [comment]
Progress tracker:
- [x] Design doc 
- [ ] Implement in Database #2563
