### ISSUE TITLE
docs: api.infrahq.com is broken/unreachable

### ISSUE THREAD

**Issue by j-sneh** [infrahq/infra#2034]
## Describe the bug

The api.infrahq.com domain used throughout the API documentation is unreachable and cannot process requests to the API.

## Expected behavior

Any response from the server, as mentioned [in the documentation.](https://api-docs.infrahq.com/reference/listaccesskeys) 

If users are not meant to use api.infrahq.com and instead ping their own infra servers, then that should be made clear in the docs.

## Screenshots

<img width="562" alt="Screen Shot 2022-05-24 at 10 27 23 AM" src="https://user-images.githubusercontent.com/25213198/170096152-2d938c47-f6bf-4c2f-b61f-e7a1c732f147.png">

## Additional context

I know there are other changes to the API like version headers, and using `/api/<request>` instead of `/v1/<request>` that are currently not reflected in the documentation that could be related.

**Comment by mxyng** [comment]
The API docs were not updated with 0.13.0 due to a CI bug. Changes like `/api/<request>` should be updated with the next release
