### ISSUE TITLE
`CommaSeparatedStrings` does not escape commas

### ISSUE THREAD

**Issue by dnephin** [infrahq/infra#2068]
We use `data.CommaSeparatedStrings` as an https://pkg.go.dev/database/sql#Scanner, and https://pkg.go.dev/database/sql/driver#Valuer for storing a list of strings.

The list of strings is encoded using a comma to separate the items in the slice, but we don't appear to validate that the items themselves don't contain commas (as far as I've seen), and we don't escape the commas.

This means that if a list of values which contain one or more commas is stored in the DB, we won't get the right value back out.

We should either validate that each item in the `[]string` does not contain a comma, or we should change the encoding to something that will escape characters as necessary.

My preference would be for a JSON encoding type, which we could use in other places for structured data. Some databases support JSON data types, and for others we can store it in a text field.

There are a few examples out there of a JSON Valuer:
* https://github.com/go-gorm/datatypes/blob/master/json.go
* https://gist.github.com/rrafal/09534862e05cd98e4eb9b17dd5fcc1fc

**Comment by jmorganca** [comment]
JSON encoding would be great here – we'd be able to query the data as well for databases that support it natively
