### ISSUE TITLE
Investigate and remove unused Infra `view` role

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#2075]
Within Infra itself, users don't have any role by default, and we currently don't make use of the built-in `view` role. New Infra users should be provided a default `view` role upon provisioning, or we should remove this role altogether if it isn't being used.

**Comment by dnephin** [comment]
Today the infra view role can be used to give a non-admin user access to:
* `ListAccessKeys`
* `ListGrants`
* `ListGroups`, and `GetGroup`
* `ListUsers`, and `GetUser`

I'm not sure if we have a use case for viewing these things without being able to add or edit them, but I guess that's the idea for this role.

**Comment by jmorganca** [comment]
Closing for now as there's a large chance this will be helpful for different kinds of admins in the near future
