### ISSUE TITLE
docs: add a section to the API reference for introducing common concepts

### ISSUE THREAD

**Issue by dnephin** [infrahq/infra#2080]
Most API reference docs start with some introduction to concepts like versioning, common headers, and authentication. Ex:
* https://docs.github.com/en/rest/overview/other-authentication-methods
* https://stripe.com/docs/api
* https://www.consul.io/api-docs

Right now we don't have a place for these things, but we have use cases for it:
* ~https://github.com/infrahq/infra/pull/2041#pullrequestreview-986445691 (the version header)~ Done
* https://github.com/infrahq/infra/pull/2045 (the Accept header)
* we don't document how to authenticate with the API, or how to get the access key used in the header

**Comment by dnephin** [comment]
Maybe one of these places in the openapi spec would allow us to add this documentation:
* https://swagger.io/specification/#info-object
* https://swagger.io/specification/#external-documentation-object

**Comment by dnephin** [comment]
We've started to document these things in https://github.com/infrahq/infra/blob/main/docs/api/making-requests.md, but we still need a way to display them from the API reference doc.

**Comment by jmorganca** [comment]
Initial front matter was added to the API docs: https://infrahq.com/docs/reference/api
