### ISSUE TITLE
ui: logging out and logging in with a OTP skips password change dialog

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#2082]
Steps to reproduce:

1. Log in as a user with a one time password
2. Create another user
3. Log in with second one time password

**Comment by hoyyeva** [comment]
this is another use case:
If user gets created with OTP, logs in, updates password, and is removed, recreating the user generates a new OTP but does not prompt to change password after using new OTP. This CLI handles this correctly by forcing the user to change their password.
