### ISSUE TITLE
ui: scrolling behavior for lists and sidebars

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#2085]
1. Longer lists cause headers to go off screen (optional)

<img width="1429" alt="Screen Shot 2022-05-26 at 2 55 50 PM" src="https://user-images.githubusercontent.com/251292/170557619-3df749c7-69c3-4590-b606-355375baaa8e.png">

2. Sidebars scrolls off-screen even when clicking on an item further in the list

<img width="1837" alt="Screen Shot 2022-05-26 at 2 40 20 PM" src="https://user-images.githubusercontent.com/251292/170559055-994513c6-48e2-42c6-a071-7f0fde935a5c.png">

**Comment by hoyyeva** [comment]
table improvement feedback from bug bash - Tables, when scrolling, should always display the header. It should probably also display the title and add button
