### ISSUE TITLE
`infra keys list` shows expired keys

### ISSUE THREAD

**Issue by j-sneh** [infrahq/infra#2087]
## Describe the bug

`infra keys list` still shows keys even after they have expired. This list can get really long if there are multiple login requests and so cleanup is necessary.

## Expected behavior

Either completely hiding the expired keys or only showing them with a verbose/all flag. 

## Screenshots

<img width="793" alt="ple com yesterday" src="https://user-images.githubusercontent.com/25213198/170562803-408669ac-81ed-4153-80ca-788c7e853b90.png">

## Environment

```
$ infra version

Client: 0.13.0
Server: 0.13.0
```

**Comment by dnephin** [comment]
I wonder if we should have a periodic process to delete expired keys. If not , then definitely being able to filter them out in the API would be great.

**Comment by BruceMacD** [comment]
I agree that cleaning up the expired keys after a certain amount of time makes sense.

**Comment by j-sneh** [comment]
infra keys list still shows keys that have not been extended, but aren't passed their expiration date
