### ISSUE TITLE
CLI error text is hidden for custom errors

### ISSUE THREAD

**Issue by kimskimchi** [infrahq/infra#2113]
## Describe the bug

Previously: 
```
./infra grants add abc abc
ERROR  unknown destination "foo"
```
Now:
```
./infra grants add abc abc
Error: forbidden
```

Will need to include these two commits in the fix: 
`17f71bca1278e977d70d596cee1f0aff4ff1fc0b`
`006defd325286aa0c1a473c3acf1e3dfecfeb8cf`
## Environment

```
$ infra version
```

```
$ kubectl version
```

**Comment by pdevine** [comment]
Tried this out by cherry-picking the two commits and it appears to be working. There does seem to be a problem when a user doesn't have access and we're displaying `Error: forbidden`. There should be a better error message for that.
