### ISSUE TITLE
Create tests for kubeconfigs to ensure they are being updated correctly

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#2139]
We need better unit tests for kubeconfigs to make sure that we don't nuke user defined sections (specifically in both the contexts and in the authinfo sections).

**Comment by dnephin** [comment]
`TestLogout` has an example of a test that does that. It shows that after logout the non-infra contexts and authInfos are still there. We could do the same thing for other commands that modify the kube config (login, use, list?)

**Comment by jmorganca** [comment]
That sounds right!
