### ISSUE TITLE
Need to show destination status to know if a cluster is still alive

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#2151]
Currently there's no way for users to know if a cluster is "active" or not – i.e. does it still exist and is it still connected to Infra. We used to use the `updated` field for this, but it should really be its own field since the cluster may not change state.

Example request:

```
GET /api/destinations/<id>

{
  ...
  "last_seen": "2022-05-31T14:43:56+00:00"
  ...
}
```

- [ ] Add `Infra-Connector-Unique-ID` header to requests from the connector to the server
- [ ] Add and update `LastSeenAt` Destination field when an authenticated request with the header is received by the server

**Comment by hemachandarv** [comment]
@jmorganca Could you please assign this to me? I'd like to address it.
