### ISSUE TITLE
Inherited grants in the API

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#2165]
Currently to answer "can user X access resource Y?", API consumers must first query `/api/grants?user=<user_id>` and `/api/grants?group=<group_id>` for every user and group that user is in. This results in a complex query with quite a few calls.

Instead, it would be preferred if the API can show "inherited" grants. I.e. `/api/grants?user=<user_id>` takes into account:
1. This user's groups
2. This user's grants to _parent_ resources (e.g. a cluster -> namespace)

**Comment by ssoroka** [comment]
answering whether or not a user can do something is more complex than this, and shouldn't be put on the client to figure out. 
 we should instead have a dedicated endpoint for this. `/api/grants/can?user=id&privilege=read&resource=xyz` where the backend simply answers the question about whether or not the user has access.

**Comment by dnephin** [comment]
The inherited grants API described in the issue would be a great improvement to the API calls we make today. The CLI and desktop agent have to perform `n+2` API (where n=number of groups) calls to get all the grants for a user. The infra connector must perform (n+1)*2 API calls (where n=number of namespaces) to get all the grants it needs.

The two suggestions in the issue description would reduce the number of calls to almost 1 in each case. The only other change we'd need to make for the connector would be to add the name of the user and name of the group to the response (similar to what we need for `AccessKey.IssuedForName`, which is tracked in #1382.


@ssoroka it's not clear to me how your proposal relates to this problem. I'm not aware of any usecase we have today that would benefit from an `/api/grants/can` API endpoint. Could you elaborate on how you see this working to solve the problem of unnecessary API calls, or possibly create a different issue if the proposal is for a different problem?

**Comment by ssoroka** [comment]
Nevermind. I agree this is useful as an optimization for clients that need to fetch all grants for a user or destination (clients that don't have a specific resource in mind).
I specified what I'd like to see in a [separate issue](https://github.com/infrahq/infra/issues/2205).

**Comment by pdevine** [comment]
Going to move this to the backlog for now. We can solve this on the client side by querying grants for the groups + parent resources.
