### ISSUE TITLE
Errors parsings Snowflake IDs that are not in the expected format should be handled

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#2171]
## Describe the bug
If an ID is encountered that is not in the expected base58 encoding this causes an error to be thrown. It has been observed in some cases that this happens unexpectedly, maybe from an older Infra version. 
```
infra login
ERROR  invalid base58: not in canonical form
```

## Expected behavior
This error should generally not be reachable since we control the creation of IDs and should validate this when IDs are generated. If it is reached we should log the error and attempt to continue or recover.

## Environment

```
infra version

 Client: 0.13.2+dev
 Server: disconnected
```

```
$ kubectl version
```

**Comment by BruceMacD** [comment]
Workaround is to try an older Infra CLI version (v0.11.0 has been seen to work).

**Comment by dnephin** [comment]
We could normalize the ids by stripping the leading `1`s from the string.
