### ISSUE TITLE
ui: roles are static/enumerated in the ui and unrecognized roles default to "view"

### ISSUE THREAD

**Issue by j-sneh** [infrahq/infra#2236]
## Screenshots

<img width="459" alt="Screen Shot 2022-06-08 at 1 32 03 PM" src="https://user-images.githubusercontent.com/25213198/173464292-97b26f35-a156-4b50-ac45-f82b3634cad2.png">

Here, the same email has different "view" roles.

## Additional context

Could be the namespace permissions?

**Comment by mxyng** [comment]
The UI currently maps roles to a static list of roles. In this case, the user is given roles that are valid in Infra but unknown to the UI so it defaults to the `view` role
