### ISSUE TITLE
Update password should only allow finite number of failures

### ISSUE THREAD

**Issue by mxyng** [infrahq/infra#2278]
## Describe the bug

Right now if password updates fails, it will reprompt the user. This reprompt can occur an infinite number of times. Instead, it should reprompt at most 3 times before exiting with error

**Comment by pdevine** [comment]
This should lockout for a period of time which should be configurable. If you lockout forever, it can cause a DOS attack.

**Comment by mxyng** [comment]
I think you're talking about a different feature: locking out successive login failures to prevent brute forcing password login. While that's also a valid feature, this issue specifically relates to successive failures _changing_ a password due to not meeting password requirements, something similar to Unix's passwd. The current behaviour will loop forever on failure which isn't ideal.
