### ISSUE TITLE
infra login should skip server selection if user sets a default

### ISSUE THREAD

**Issue by mxyng** [infrahq/infra#2369]
## Is your feature request related to a problem? Please describe.

If users have multiple servers cached in their config, it's tedious to have to select a server with each invocation of `infra login`. Currently the only way to skip server selection is to provide the server with `infra login <server>` but it's easy to forget the server.

## Describe the solution you'd like

A good solution is setting the server from an environment variable. This gives the user flexibility in how they can use infra. The default can be set globally in shell profiles or locally per session as needed.

```
$ INFRA_SERVER=localhost
$ infra login
  Logging in to localhost
? Select a login method: okta (dev.okta.com)
  Logging in with okta...
  Logged in as user@email.com
```

## Describe alternatives you've considered

An alternative may to allow users to set a default such that if an override isn't supplied, it will use the default.

## Environment Details

```
$ infra version
```

```
$ kubectl version
```

**Comment by pdevine** [comment]
This is important to fix. Shouldn't this be in a CLI argument and not an environment variable though?

**Comment by pdevine** [comment]
Actually, we already have the positional argument. I'm not sure why we would also need to support the environment variable as well. Going to close this for now.

**Comment by dkulchinsky** [comment]
> Actually, we already have the positional argument. I'm not sure why we would also need to support the environment variable as well. Going to close this for now.

Hey @pdevine 👋🏼 

Can you clarify this point? how would we use this?

primarily, we were looking for a way for users to login to server (once) and set it as "default", so that subsequently they only need to run `infra login` and they "default" server/provider combo will be used.

**Comment by pdevine** [comment]
Hey @dkulchinsky, I think I misunderstood the request here. I read it as just setting an environment variable vs. just setting the the positional argument of the user. I'll go ahead and re-open.

**Comment by j-sneh** [comment]
You can already set the INFRA_SERVER environment variable to skip server selection using the current CLI.
