### ISSUE TITLE
Reduce the access package

### ISSUE THREAD

**Issue by dnephin** [infrahq/infra#2431]
## Background

The `access` package provides authorization for the API, but it also acts as a layer between the API handlers and the data layer. Generally a separation between an http-specific interface and a purely domain-logic interface is a great thing. It makes it easier to expose the core functionality via different public interfaces.

In our case, our API framework (in `routes.go`, built on top of `gin`) already handles all the HTTP specific concerns generically. Our "API handlers" are already a pretty nice domain-logic interface, without anything really http-specific about them. Because of this our `access` package ends up being an almost 1-1 mirror of the "API handlers", which often makes code hard to write. It's rarely clear if logic should go into the access package or the http handler.

## Proposal

We should reduce the `access` package to just a few exported functions and types:
```go
type AuthorizationError struct { ... }

func RequireInfraRole(txn data.ReadTxn, roles ...string) error { ... }
```

This would let us collapse the access functions into the api handlers and make it one less layer to trace when reading the code.

**Comment by ssoroka** [comment]
This is defeats one of the goals of the access package: to make sure developers have thought about what kind of access controls they need in place before accessing data. I don't think this is a change in the right direction.
