### ISSUE TITLE
Add destination cleanup loop

### ISSUE THREAD

**Issue by mxyng** [infrahq/infra#2440]
Add a running loop to cleanup old destinations. If a destination has `LastSeenAt` older than 1h, delete it.

**Comment by dnephin** [comment]
We have a similar problem with access keys. We don't currently prune them after they expire, even though they will never be useful again.

A destination still has some value after it is inactive. The operator can see it's inactive and fix the problem.

I think 1 hour is much too short of a threshold to delete it. An outage in a cloud provider could easily lost more than an hour.

I think we should hold off on solving this problem and address it for all types (access keys, destinations, etc). I expect the inactive threshold will need to be more like 3 days, to account for dev clusters that could be left inactive during a long weekend.

**Comment by dkulchinsky** [comment]
> A destination still has some value after it is inactive. The operator can see it's inactive and fix the problem.
> 
> I think 1 hour is much too short of a threshold to delete it. An outage in a cloud provider could easily last more than an hour.

just adding my 2-cents here, but I agree with @dnephin, a destination could be down for much longer than an hour due to scheduled maintenance of the cluster, cloud outage etc, perhaps this should be configurable? or at least set to something like 24 hours
