### ISSUE TITLE
Use a scheduled job to clean up stale or expired database entries

### ISSUE THREAD

**Issue by dnephin** [infrahq/infra#2498]
We have a number of issues about pruning stale/expired items:
* expired access keys
* #2440
* #1726
* device codes for device flow
* any old soft-deleted records

We need some way to periodically remove these and other entities that are stale. We could do that in a background goroutine in the server, but we expect that in large deployments there could be many server replicas to handle all the API requests.

Instead of a background goroutine we can use a [kubernetes cronjob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/). The job would be deployed as part of the server deploy with helm. 

The job should be a separate command (maybe `infra server pruner`) that queries for any stale or expired entries, and deletes them.

**Comment by BruceMacD** [comment]
#3542
