### ISSUE TITLE
DB migrations tests fail if additional fields are added to the base model

### ISSUE THREAD

**Issue by pdevine** [infrahq/infra#2564]
## Describe the bug

In `data/migrations.go` we call `initializeSchema()` which calls `db.Automigrate()` with each of the models. This works fine with our existing model because none of the older migrations need to call `ALTER TABLE` on newer tables (such as `provider_user`). If you add another field to the base model, it will end up trying to alter every table with the new field, which fails because not every table exists in our older migrations.

The failure (in `make test`) will look something like:
```
--- FAIL: TestMigration_202204111503 (0.01s)
    writer.go:25: {"level":"info","time":1657653584313,"caller":"logging/logger.go:76","message":"running migration 202204111503"}
    writer.go:25: {"level":"error","rows":0,"query":"ALTER TABLE `provider_users` ADD `organization_id` integer","elapsed":0.005542,"error":"no such table: provider_users","time":1657653584319,"caller":"migrator/migrator.go:328"}
    migrations_test.go:29: assertion failed: error is not nil: migration failed: no such table: provider_users
--- FAIL: TestMigration_202204211705 (0.01s)
    writer.go:25: {"level":"error","rows":0,"query":"ALTER TABLE `provider_users` ADD `organization_id` integer","elapsed":0.005125,"error":"no such table: provider_users","time":1657653584325,"caller":"migrator/migrator.go:328"}
    migrations_test.go:44: assertion failed: error is not nil: migration failed: no such table: provider_users
```

## Expected behavior

We need to account for the proper state of the database when we're performing the migrations.

## Additional context

You can add any field to `models.Model` to replicate this.

**Comment by ssoroka** [comment]
don't quite understand this. initializeSchema is only called in two scenarios:
1. after the migrations to support adding new fields that don't require migrations.
2. on a fresh database that has never been initialized.

If I understand this, you're having problems with #2? a fresh database that creates these fields and then tries to apply the migration afterwards? Migrations should probably have guards that check if anything needs to happen for this case.

**Comment by pdevine** [comment]
It's pretty easy to replicate. Just add another field to `models.Model` and run `make test`. I'm assuming I was running into scenario #2 as you mentioned.

**Comment by pdevine** [comment]
I'm going to close this. What ended up happening was the `Provider User` table didn't end up having the base model and I was including it in the tables to migrate which caused things to blow up.
