### ISSUE TITLE
Default key TTL is too short to use with infra CLI

### ISSUE THREAD

**Issue by mxyng** [infrahq/infra#2640]
## Describe the bug

By default, infra CLI issues an access key for 720h (30d). The default session duration is also 720h (30d). There's a server-side check to ensure the new access key exchanged in a login does not expire after the original key. So if using all default values, all keys issued by infra CLI will be unusable except in raw HTTP requests

**Comment by pdevine** [comment]
We should remove access key exchange in the CLI (i.e. you should just use the access key directly)
