### ISSUE TITLE
Add destination name label to infra_destinations metric

### ISSUE THREAD

**Issue by dkulchinsky** [infrahq/infra#2664]
## Is your feature request related to a problem? Please describe.

We are looking for a way to proactively monitor and alert (using prometheus metrics & alerts) when destinations have been disconnected from the server for more than X duration.

The recent enhancement in https://github.com/infrahq/infra/pull/2560 is very helpful, but only provides a count of connected vs disconnected destinations.

This is useful, but difficult to provide actionable information in an alert that should be able to identify the failing destination(s).

## Describe the solution you'd like

We would like to destination name to be added to the label in the `infra_destinations` metric, this will allow us to identify the specific destination(s) that is failing and make the alerts more meaningful.

## Describe alternatives you've considered

None that apply

I'm aware that this will increase cardinality of said metric, however I think the risk & potential impact is fairly low, destinations are managed entities and even an increase of say 1K time-series is generally a non-issue for Prometheus, perhaps to mitigate this can be a default opt-out and be configurable, or can be split to a separate metric so can be skipped during scrape/ingestion.

## Environment Details

```
$ infra version
```

```
 Client: 0.13.6
 Server: 0.13.6
```

```
$ kubectl version
```

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:21:56Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8-gke.2200", GitCommit:"81a23326454f32475752ab4ef1ebdd164a6ba96d", GitTreeState:"clean", BuildDate:"2022-04-13T09:37:04Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mxyng** [comment]
@dkulchinsky server <-> connector metrics has been added though not in the way originally described in the issue. As of https://github.com/infrahq/infra/pull/3200, the _connector_ will now report a new `http_client_request_duration_seconds` histogram metric (so `http_client_request_duration_seconds_{sum|count|buckets}`) for requests to the Infra server. 

This metric has similar labels as the server's `http_request_duration_seconds` metric:

- `host` describes the destination address. In this case, the HTTP server the request was sent to
- `method` describes the HTTP method used
- `path` describes the request path
- `status` describes the HTTP status or `-1` if there's an error with the request

With this information, you should be able to quickly and conclusively identify which connectors may be having trouble connecting to the server.

**Comment by dkulchinsky** [comment]
Hey @mxyng, thanks a lot for working on this and for the summary 👍🏼 

This is definitely going to improve observability on connector --> server path 👏🏼
