### ISSUE TITLE
ui: add button should be fully visible when ui takes up half screen

### ISSUE THREAD

**Issue by j-sneh** [infrahq/infra#2695]
## Describe the bug

The add button isn't fully in view when any page is half-size. 

## Expected behavior

The UI should be equally as functional when filling half a screen.

## Screenshots

<img width="756" alt="Screen Shot 2022-07-22 at 12 15 15 PM" src="https://user-images.githubusercontent.com/25213198/180509527-3872712d-cc83-429d-b098-773c3c9dc21c.png">

**Comment by jmorganca** [comment]
This should be fixed on `main`
