### ISSUE TITLE
Allow connector.config.name string as 2  

### ISSUE THREAD

**Issue by yeshwanth1312** [infrahq/infra#2701]
When using connector.config.name as two strings , we are seeing errors which is connector.config.name=k1 , Allow 2 strings to be passed , We did not face this issue in before version 

Below error says must be atleast 3 

Helm command 
```
helm upgrade --install infra-connector infrahq/infra --set connector.service.type=ClusterIP --set connector.config.name=k1 --set connector.config.server=_aws_elb_endpoint_ --set connector.config.accessKey=****** --set connector.config.skipTLSVerify=true -n infra


## Screenshots


```
level":"warn","time":1658525748787,"caller":"logging/logger.go:79","message":"registering Kubernetes connector with ClusterIP. it may not be externally accessible. if you are experiencing connectivity issues, consider switching to LoadBalancer or Ingress"}
{"level":"error","time":1658525748793,"caller":"logging/logger.go:83","message":"initializing destination: error creating destination: validation failed: name: length of string is 2, must be at least 3"}
```
Below is error on server pod


## Environment

<!-- Infra client and server versions using `infra version` -->

```
$ infra version
```
infra version

 Client: 0.14.0
 Server: 0.14.0

<!-- Kubernetes version using `kubectl version` -->

```
$ kubectl version
```

<!-- Where you are running Kubernetes (e.g. EKS, AKS, GKE, Docker Desktop, Minikube, etc.) -->

## Relevant Infra Logs

<!--
Use `kubectl logs deployment/infra-server` and `kubectl logs deployment/infra-connector` and
add any suspicious logs here. Try to keep snippets short and concise.

Sensitive information should be masked/redacted.
-->

## Additional context

<!-- Add any other context about the problem here. -->

**Comment by dnephin** [comment]
Thank you for the bug report! We did introduce some stricter validation for name fields in v0.14.0. Sorry this has caused you problems. We are introducing the validation as strict as possible now, to avoid this very problem in the future.

I should have called this out as a breaking change. I will update the changelog to identify it as such.

If you `helm upgrade` the connector again with `--set connector.config.name=k01` it should fix the error. Does that work for you? If the old connector is still shown in `infra destinations list`, you can run `infra destinations remove k1`.

**Comment by yeshwanth1312** [comment]
Yeah that works .. but some of our clusters named with two strings . would be nice to get it back . So we can have parity
