### ISSUE TITLE
Fix default fsGroup in helm

### ISSUE THREAD

**Issue by fsdaniel** [infrahq/infra#2740]
## Describe the bug

0.14.1 introduces running process as infra (UID/GID) 1000.
As no podSecurityContext is passed by default mount is done as root making it unable for app to write data to it.

## Expected behavior

Server comes online.

## Screenshots
```
{"level":"error","time":1658864558395,"caller":"logging/database.go:29","message":"failed  to initialize database, got error unable to open database file: no such  file or directory"}
```

## Environment
```
infra: 0.14.1

```

```
kubernetes: v1.22.9
```

## Relevant Infra Logs
```
{"level":"error","time":1658864558395,"caller":"logging/database.go:29","message":"failed  to initialize database, got error unable to open database file: no such  file or directory"}
```

## Additional context

- Information on security context: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
- change in 0.14.1: https://github.com/infrahq/infra/commit/c21623d27875815b5d749a744912121ccb7a8486

**Comment by mxyng** [comment]
Fixed in #2741
