### ISSUE TITLE
Don't prompt in `infra login` when info is already known

### ISSUE THREAD

**Issue by joeshaw** [infrahq/infra#2758]
This is related to #2557 but I think it's a distinct issue.

I would like for subsequent runs of `infra login` after the first setup to do the needful without prompting me.

For some background, I initially configured infra by running `infra login --provider okta infra.example.com`.  I only use the one server and the one login method, and I find it annoying that each subsequent time I need to run `infra login` that I either (a) need to provide the server and provider again or (b) hit enter through some prompts.

```
$ infra login
? Select a server:  [Use arrows to move, type to filter]
> infra.example.com
  Connect to a new server

? Select a login method:  [Use arrows to move, type to filter]
> okta (example.okta.com)
  Login with username and password
```

My preferred solution would be for `infra login` to use the saved config and do it without prompting if there is a previously configured server.  An also acceptable solution would be to have a flag to do this, like `infra login -y`.  My argument for the former is that the vast majority of the time people will only have a single login and want to use it (or log into their most recently used server if there's more than one).  Also this would match other tooling that performs similar things like `kubectl oulogin`.

## Environment Details

```
$ infra version
 Client: 0.14.2
 Server: 0.14.1
```

```
$ kubectl version
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.22.8
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
```

**Comment by dkulchinsky** [comment]
I believe this is similar to what I've described in https://github.com/infrahq/infra/issues/2369?

**Comment by j-sneh** [comment]
With the most recent CLI, you can already set the `INFRA_SERVER` environment variable to skip the first step.

**Comment by dkulchinsky** [comment]
> You can already set the `INFRA_SERVER` environment variable to skip the first step with the current CLI.

Thanks @j-sneh, but even if we set the `INFRA_SERVER` env variable, it still prompts and asks to choose the provider:

```
❯ export INFRA_SERVER=<our server fqdn>
❯ infra login
? Select a login method:  [Use arrows to move, type to filter]
> okta (<our okta domain>)
  Login with username and password
```

OTOH and through pure guessing, I also set the `INFRA_PROVIDER=okta` env var and voila:

```
❯ export INFRA_SERVER=<our server fqdn>
❯ export INFRA_PROVIDER=okta
❯ infra login
  Logging in with okta...
  Logged in as my@email
```

I think the above gets us the same kind of UX (wdyt @joeshaw?)

though, I would prefer if this was more intuitively controlled via the cli as Joe initially suggested.

**Comment by j-sneh** [comment]
@dkulchinsky @joeshaw As it turns out, any flag can be implicitly filled in by an environment variable if it follows the convention: `INFRA_FLAG_NAME` --> `--flag-name`. I'll update the docs to better reflect this.

I'm not sure if we want to modify the config (@dnephin), but for now the environment variables should work well enough.
