### ISSUE TITLE
ui: logout error

### ISSUE THREAD

**Issue by hoyyeva** [infrahq/infra#2773]
![Image](https://user-images.githubusercontent.com/63033505/181785234-c7fee800-896c-4883-9ff1-0d9938bcbfa2.png)

**Comment by BruceMacD** [comment]
I wasn't able to reproduce this one today on main

**Comment by BruceMacD** [comment]
This triggers after you refresh the page.
Reproduction steps:
- login
- do some stuff
- refresh the page
- click logout
