### ISSUE TITLE
ui: adding a user to groups changes sort order and formatting

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#2823]
Adding a user to a group has two disorienting visual effects:

1. The sort order changes while adding a user (major)
2. The sidebar formatting changes slightly when selecting a user in the dropdown (minor)

https://user-images.githubusercontent.com/251292/182921900-30e2c272-ede5-40c6-b756-249f0d18f838.mov

**Comment by j-sneh** [comment]
This is definitely from removing the client-side CreatedAt sort. We can re-add that temporarily. However, we will need to paginate this response eventually (once there are >100 users in a group), so we'll need to design a solution for that in the UI and add server-side sorting.
