### ISSUE TITLE
ui: login with Azure Active Directory

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#2883]
<img width="301" alt="Screen Shot 2022-08-09 at 11 00 46 AM" src="https://user-images.githubusercontent.com/251292/183685459-1888c2a8-0c21-4088-a465-cba398951b9d.png">

For now we should rename this to "Login with Azure Active Directory" or "Login with Azure AD"

Eventually we should rename this to "Login with Microsoft" with the standard Microsoft logo

**Comment by hoyyeva** [comment]
fixed on main already
