### ISSUE TITLE
Org specific `/.well-known/jwks.json` domains

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#2958]
## Describe the bug
The connector is currently making a call to the /.well-known/jwks.json to check JWK info. 

## Expected behavior
The connector validates the JWT signature using an org specific JWK at `org.domain.com/.well-known/jwks.json`, this JWK is unique for the org.

## Additional context
This JWK org domain could come from an introspect call on the connector's access key. Other options are also possible.

**Comment by dnephin** [comment]
If we go with https://github.com/infrahq/infra/issues/2960, we could use the access key (which the connector needs anyway) and use the org ID from the access key.

**Comment by ssoroka** [comment]
The connector already uses the host. My preference is to specify the host for the domain. There is no requirement to use multiple orgs in a single connector.

**Comment by BruceMacD** [comment]
Fixed in org implementation, local use-case in #3083
