### ISSUE TITLE
Proposal: reading organization ID from an API request

### ISSUE THREAD

**Issue by dnephin** [infrahq/infra#2960]
The organization ID can be provided in two ways:
1. all access keys are part of an org, so the org can be looked up by the access key used to make the API request
2. each org has a domain name, so the org can be looked up from the `Host` HTTP header

Currently we also support an `Infra-Organization` HTTP header, but this is functionally not any different from the hostname, and we could choose to remove it at any time. So for this proposal the  `Infra-Organization` HTTP header is ignored.

I propose the following behaviour:

:round_pushpin: - indicates where the proposed behaviour is different from `main` today
:asterisk: - indicates where the behaviour matches the proposal, but to perform the DB query in a transaction we need to re-order the logic so that domain lookup happens after the transaction is started.

|  Request  | Authenticated Endpoints | Unauthenticated Endpoints |
| --- | --- | --- |
| Access key only | Org ID from access key  | Org ID from access key :round_pushpin: |
| Hostname only | 401 Unauthorized | Org ID from hostname :asterisk: |
| Both access key and hostname agree on the org | Org ID from either | Org ID from either |
| Access key and hostname specify different orgs | 400 Bad Request | 400 Bad Request :round_pushpin:  |
| Neither access key or hostname | 401 Unauthorized | Depends on the endpoint and server config, see [comment below](https://github.com/infrahq/infra/issues/2960#issuecomment-1218952132). |

If the hostname from the HTTP request does not match any org domain then it's equivalent to not specifying a hostname. The hostname is ignored, so it would count as "access key only" or  "neither access key or hostname".

This allows a user to use an access key in all cases once they have logged in. Before login they must use the correct hostname to identify the org they are trying to login to.

**Comment by dnephin** [comment]
Given the table above, a modified version of [organization request flow](https://github.com/infrahq/infra/blob/main/docs/dev/organization-request-flow.md)  for the last box would look like this:

```mermaid
flowchart TD
    A[Incoming Request with no access key and no hostname match] --> AD

    AD{Is multi-tenant?} %% is signup enabled
    B{endpoint requires org?}

    AD --> |Yes| B
    AD --> |No| AF[200 OK - use default org]
    B --> |Yes| C{HTTP method}
    C --> |"GET"| E[200 OK - with fake data]
    C --> |"POST"| AB[400 Bad Request]
    B --> |No| D[200 OK - no org necessary]
```

**Comment by ssoroka** [comment]
please move to notion
