### ISSUE TITLE
Connector deploys with a "postgres" stateful set

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#2979]
## Describe the bug
When deploying the connector a new "infra-connector-postgres" stateful set is deployed alongside it.

## Expected behavior
The connector shouldn't need persistence.

## Screenshots
<img width="1440" alt="Untitled" src="https://user-images.githubusercontent.com/5853428/185608561-f70e1786-0425-45cd-bf67-0cc9a5814c2f.png">

## Environment
mainline dev

## Additional context
```
helm install infra-connector helm/charts/infra --set connector.config.name=docker-desktop --set connector.config.accessKey=${CONNECTOR_KEY} --set connector.config.server=dev.acme.internal --set global.image.pullPolicy=Never --set global.image.tag=dev
```

**Comment by mxyng** [comment]
Closed by #3034
