### ISSUE TITLE
Rollback transactions in middleware does not have an effect

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#3076]
## Describe the bug
The way we currently handle runtime errors means that errors are never fully bubbled up to our middleware database transaction, so errors would not cause a database transaction rollback.

## Expected behavior
Database transactions are handled in a way that can receive the error and rollback appropriately. 

## Environment
- Infra version <=0.14.5

## Additional context
```
// middleware.go
func withDBTxn(ctx context.Context, db *gorm.DB, fn func(tx *gorm.DB)) {
	err := db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		fn(tx)
                // need to return an error here if the function fails
		return nil
	})
	// TODO: https://github.com/infrahq/infra/issues/2697
	if err != nil {
		logging.L.Error().Err(err).Msg("failed to commit database transaction")
	}
}
```

**Comment by BruceMacD** [comment]
Related: #2697

**Comment by dnephin** [comment]
I think I have a reasonable fix for this
