### ISSUE TITLE
When only local login is available the "OR" bar should not be displayed at login

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#3102]
## Describe the bug
![image](https://user-images.githubusercontent.com/5853428/188008707-e4b33d8b-3a8f-4911-8443-20159fcb31f2.png)

## Expected behavior
Only the one login method is displayed.

**Comment by mxyng** [comment]
I believe there's other problems at play here. The UI correctly display the login when no providers are configured. If you can reproduce this, please reopen it with more details

![image](https://user-images.githubusercontent.com/2372640/188241745-42af2836-aa31-4a70-8729-fc3d9531c403.png)
