### ISSUE TITLE
Connector should be able to update itself

### ISSUE THREAD

**Issue by igorcoding** [infrahq/infra#3154]
## Is your feature request related to a problem? Please describe.

When we upgrade an Infra server it is really inconvenient to update each connector in all of the connected clusters manually, because they've been installed manually via a command generated by Infra server.

## Describe the solution you'd like

Connector, while connected to the server should receive a command from the server to upgrade itself to the specified version to match a server. Also this behaviour should be optional - so teams that install connector via automated tools could still do the upgrade process manually.

**Comment by mchiang0610** [comment]
Hey @igorcoding thanks for suggesting this feature. It's definitely a good experience to have automatic updates on the connectors. There are security challenges we'll face when navigating this. 

Curious on your end, how many connecters are you running today? Do you plan to use infrastructure as code tools like Terraform to deploy infra connectors?

**Comment by igorcoding** [comment]
Currently we have 6 clusters connected to infra, more to come. The majority of them are managed completely using Terraform, including a cluster with infra server. But some clusters exist without Terraform setup. I want to mention that connecting a new cluster is pretty easy using a "fire-and-forget" command and allows quick adding and removing of clusters. And if those connectors could manage themselves as an option it'll be great.

**Comment by igorcoding** [comment]
Well, still a nice feature to have I think
