### ISSUE TITLE
Access is provided but not able to see and list pods 

### ISSUE THREAD

**Issue by yeshwanth1312** [infrahq/infra#3281]
## Issue with kubectl get * even though user has access to cluster 

```
09:16 $ infra use k5
Switched to context "k5".
✔ ~/tremor
09:23 $ kubectl get pods -n app
error: the server doesn't have a resource type "pods"
```

Infra is working in all clusters besides two clusters 

Please let us know the reason why we would see this 

Not sure 

## Environment

```
$ infra version
```

```
$ kubectl version
```

**Comment by dnephin** [comment]
Thanks for raising this issue! I believe that error message can be printed any time `kubectl` has trouble listing resources in the cluster, so we'll need more information to find the source of the problem.

Does this problem persist, or is it intermittent?  Does it happen to all users in that cluster, or only some?

What version of infra server, infra CLI, and infra connector are being used in that cluster?

If you can share this information it should help us debug the problem:

1. The output of `kubectl get pods --v=99 -n app`. The `--v=99` should print the full debug log
2. The infra-connector logs for the connector pod running in that cluster. There may be errors in that log that point to the problem.  It'd be great to capture the log shortly after you run the kubectl that errors, so we know where to look.
3. A copy of the kube config file that is used when that `kubectl` command errors, with anything sensitive removed or redacted. 
4. The output of `infra grants list`, and `infra destinations list`

**Comment by mchiang0610** [comment]
@yeshwanth1312 I wanted to follow up to see if you are still having this problem? Would love to troubleshoot this with you if you are still running into this.

**Comment by yeshwanth1312** [comment]
Hi @mchiang0610  sorry for the delay, Yes we are still facing this issue.

We have two AD groups, Admin and Dev. These issues are related to the Dev group. What is the best way to send the requested info? via email or here? Do we have a slack channel for Infra?

Thanks
