### ISSUE TITLE
website: first load seems broken

### ISSUE THREAD

**Issue by hoyyeva** [infrahq/infra#3386]
## Describe the bug
- Go to infrahq.com
- The page loads slowly and it seems broken for couple second until its fully loaded

## Expected behavior
- should have a loading state while waiting for the data to be loaded

## Screenshots

<img width="1279" alt="Screen Shot 2022-10-04 at 11 21 29 AM" src="https://user-images.githubusercontent.com/63033505/193859696-967a7a28-414a-4f77-9246-bfae9ca6deed.png">

**Comment by BruceMacD** [comment]
This seems like it may be resolved now? There is a quick flash of no content, but its fast enough that Im not sure a loading state is needed
