### ISSUE TITLE
Accept the access key in request headers when not preceeded by the `Bearer` prefix

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#3558]
## Describe the bug
Authorized requests to Infra must have the authorization header of the form:
`--header 'Authorization: Bearer aaa.bbbbbbbb'`

These requests fail without the `Bearer` prefix, which is confusing.

## Expected behavior
Requests with the access key directly should work if the key is valid:
``--header 'Authorization: aaa.bbbbbbbb'`

**Comment by ssoroka** [comment]
is this behavior supported anywhere else? Maybe we can just tell them they're missing `Bearer`?

**Comment by BruceMacD** [comment]
The place it is confusing is when setting up SCIM provisioning. When Okta asks to the bearer token they don't preface it with `Bearer` then the SCIM requests fail without proper feedback.
