### ISSUE TITLE
Ability to add Ingress domain in infra-connecter 

### ISSUE THREAD

**Issue by M1doriya** [infrahq/infra#3588]
## Is your feature request related to a problem? Please describe.

Hi Team, 
I was trying out infra as an access control solution. One issue I came across is that we cannot define ingress for connector and provide `EndpointAddr` in helm values file for connector.

What Im trying to achieve:
* Use existing private load balancer as ingress for connector instead of provisioning new one. 
* Pass the private ingress domain for connector in helm values so `infra-connector` config map have [`endpointaddr`](https://github.com/infrahq/infra/blob/main/internal/connector/connector.go#L41)
* Get infra-connector CA cert for ingress domain 

## Describe the solution you'd like

Ability to add ingress for connector in helm chart only so ca-cert will be will properly and we can utilize existing ALB instead creating new one.

## Describe alternatives you've considered
Steps:
* Created separate ingress file for infra-connector service
* Edited `infra-connector` configmap manually to add `endpointaddr` variable in yaml config. (after next helm upgrade variable was removed)

By this way i was able to connect to cluster but got the error 
> Unable to connect to the server: x509: certificate signed by unknown authority

after checking the cert for infra-connector got to know that cert is for Common Name: infra-connector and not the ingress domain.
If i execute ` kubectl --insecure-skip-tls-verify get pods` then im able to get the output from the cluster for the added cluster. 

## Environment Details

```
$ infra version

 Client: 0.16.1
 Server: 0.16.1
 
$ Helm chart version : 0.20.5
```

```
$ kubectl version
1.23
```

EKS

**Comment by M1doriya** [comment]
Quick Update:
By using the NodePort service I was able to achieve desired private connectivity while allowing a minimal number of exposed ports.

**Comment by mxyng** [comment]
Hi @M1doriya! Thanks for creating this issue. Are you still having issues after switching to NodePort or does that resolve your issues?

Re: Ingress, we have so far elected to not support Ingress as it represents a higher configuration overhead to the user. The connector reports its CA such that clients can establish trust with the connector. To do this with Ingress requires the Ingress to not terminate TLS. 

This configuration differs by controller, usually through annotations. This presents a problem for the end user as the chart cannot provide a reasonable default. At the same time, the passthrough configuration can easily be missed, causing usability problems. Some Ingress controllers do not enable TLS/SSL passthrough by default so this requires modifying the ingress controller.

So far, existing service types provide a simpler setup experience so we have decided to omit Ingress until there's a more concrete use case. 

Do let me know if you have more questions or need further help!

**Comment by M1doriya** [comment]
Hi, My issue was resolved after using the NodePort configuration. 
Regarding ingress now the design of the application makes much more sense.

Infra is surprisingly easy-to-use application for k8s access control, kudos to the team.
