### ISSUE TITLE
Proposal: Add new API endpoint for login details, to replace three existing unauthenticated endpoints

### ISSUE THREAD

**Issue by dnephin** [infrahq/infra#3599]
## Background

Today we have `GetProvider`, `ListProviders`, and `GetSettings` as unauthenticated endpoints. We made them unauthenticated because we need data from them for login. The problem is that both Providers and Settings have sensitive fields that we don't want to expose to unauthenticated requests.

One option for solving this is filtering the response fields based on the request (ex: https://github.com/infrahq/infra/pull/3553#discussion_r1016948429).  In `GetSettings` we only return the non-sensitive fields right now, but it's very likely that will need to change at some point as organizations get more settings.

Also interesting to note that it seems that `GetSettings` is not used. I think we ended up reporting the password requirements from the server, instead of telling users about it ahead of time. `GetProvider` is only used potentially unauthenticated by `infra info` (it could store the provider name or omit it when unauthenticated). `ListProviders` is used by login.

## Proposal

I think we can make these endpoints safer by creating a new unauthenticated endpoint `GET /api/login-prompt` (or something like that). This endpoint would return all of the details needed for a login by the UI or CLI (or other API integration): a list of providers (but only the fields we need for login). In the future we can add things like password requirements, allowed login methods (provider, device flow, or user/pass).

This change would allow us to:
1. delete the `GET /api/settings` endpoint (maybe we can do this anyway), or make it an authenticated endpoint for when we return more details from it
2. change `GET /api/providers` and `GET /api/providers/:id` to require authentication

**Comment by BruceMacD** [comment]
Note: when making this change add `allowedDomains` to the List/Get provider responses
