### ISSUE TITLE
API docs version should default to current version

### ISSUE THREAD

**Issue by technovangelist** [infrahq/infra#3662]
## Describe the bug

Every call to the API requires Infra-Version set in the header. The OpenAPI json doc sets the example for every instance to 0.0.0 when it really should be something usable. Let's set this to the current version of the docs, or at least something recent.

**Comment by dnephin** [comment]
We used to do this, but it breaks every time we do a release. I think we need to set this version as part of publishing docs, not trying to change the copy we have in the repo.

**Comment by technovangelist** [comment]
ok, I am doing this, but was thinking it should be someweher else. but this makes sense.
