### ISSUE TITLE
Lots of info is missing in the openapi3 json doc for parameters

### ISSUE THREAD

**Issue by technovangelist** [infrahq/infra#3664]
## Describe the bug

For the docs generated by openapi, we need to have a description for all the parameters, otherwise folks won't be able to use the docs. But there is a lot of missing info. I started putting together a table of whats missing, but it will be a huge table. Can we make sure everything has a Description, Example, and Format?

This table has an X for everything that is missing in the first few hundred lines of the json doc

| schema             | parameter name               | description | example | format |
| ------------------------ | ---------------------------- | ----------- | ------- | ------ |
| CreateAccessKeyResponse  | accessKey                    | X           | X       | X      |
|                          | id                           | X           |         |        |
|                          | issuedFor                    | X           |         |        |
|                          | name                         | X           | X       | X      |
|                          | provider                     | X           |         |        |
| CreateGrantResponse      | group                        | X           |         |        |
|                          | id                           | X           |         |        |
|                          | priviledge                   |             | X       | X      |
|                          | resource                     |             | X       | X      |
|                          | user                         | X           |         |        |
|                          | wasCreated                   | X           | X       | X      |
| CreateTokenResponse      | token                        | X           | X       | X      |
| CreateUserResponse       | id                           | X           |         |        |
|                          | name                         | X           | X       | X      |
|                          | oneTimePassword              | X           | X       | X      |
| Destination              | connected                    | X           | X       | X      |
|                          | connection.ca                | X           |         | X      |
|                          | connection.url               | X           |         | X      |
|                          | name                         | X           | X       | X      |
|                          | resources                    | X           | X       | X      |
|                          | roles                        | X           | X       | X      |
|                          | uniqueID                     | X           |         | X      |
|                          | version                      | X           | X       | X      |
| DeviceFlowResponse       | deviceCode                   |             |         | X      |
|                          | userCode                     |             |         | X      |
|                          | verificationURI              |             |         | X      |
| DeviceFlowStatusResponse | deviceCode                   | X           |         | X      |
|                          | login.accessKey              | X           | X       | X      |
|                          | login.name                   | X           | X       | X      |
|                          | login.organizationName       | X           | X       | X      |
|                          | login.passwordUpdateRequired | X           | X       | X      |
|                          | login.userId                 | X           |         |        |
|                          | status                       |             | X       | X      |
| Grant                    | group                        | X           |         |        |
|                          | id                           | X           |         |        |
|                          | privilege                    |             | X       | X      |
|                          | resource                     |             | X       |        |

The result in the docs is this:
![CleanShot 2022-11-17 at 09 22 44](https://user-images.githubusercontent.com/633681/202514795-fea925c6-fe8e-4398-826f-628370f6e9bb.png)

I would do it, but I can't figure out where to go to do it.

**Comment by ssoroka** [comment]
let's chat about this. every `id` and `issuedFor` indeed have examples and formats.

**Comment by technovangelist** [comment]
ok, I see where a lot of this is set now. I'll go through and take a stab at cleaning this up
