### ISSUE TITLE
login via UI is not working

### ISSUE THREAD

**Issue by yeshwanth1312** [infrahq/infra#3748]
Hello 

Q: How does UI component connect to the Server? I don't see anything in helm chart that tells UI to which backend server it needs to connect 

We are self-hosting Infra , See the below screenshots
<img width="694" alt="image" src="https://user-images.githubusercontent.com/34922578/204333670-cb888c40-8f52-4ab6-9c97-6aabea7f432b.png">

# Devloper tools info below
````
Request URL: http://*redacted*:3000/api/login
Request Method: POST
Status Code: 404 Not Found
````

**Comment by jmorganca** [comment]
Hi @yeshwanth1312 

You'll want to make sure the server is configured in the helm chart to point at the UI. The default configuration is:

```
server:
  config:
    ui: proxyURL: http://infra-ui:3000
```

Then visit the _server_ endpoint. In your case this is probably `https://<redacted>/login. (PS: make sure to always use HTTPS when connecting to Infra's API or UI)

Will close this for now, but feel free to re-open if this doesn't solve it for you

**Comment by yeshwanth1312** [comment]
Also, i am granting everyone in AD group as admin to infra resource, but I see below error 

 `infra login server-url` is working though 

```
infra keys add --connector --ttl 17520h0m0s
Cannot list keys: missing privileges for GetUser
```
## values.yaml file
```
    ## Additional grants to configure
    grants:

      - group: SSO-Infra-Admin
        role: admin
        provider: azure
        resource: infra

```

Error logs

```
level":"debug","error":"you do not have permission to list users, requires role admin, view, or connector","method":"GET","path":"/api/users","statusCode":403,"remoteAddr":"redacted:43461","time":1669656839790,"caller":"server/routes.go:192","message":"api request error"}
{"level":"info","method":"GET","path":"/api/users","localAddr":"ireddacted","remoteAddr":"redacted","userAgent":"Infra/0.16.2 (cli 0.18.1; darwin/arm64)","userID":"redacted","orgID":"if","elapsed":2.820692,"statusCode":403,"size":106,"time":1669656839790,"caller":"server/logging.go:80","message":"API request completed"}
{"level":"debug","time":1669656898031,"caller":"server/middleware.go:239","message":"Host: iredacted"}
```

@jmorganca  Can you please check this as well
