### ISSUE TITLE
Document where to Download old CLI Versions 

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#3754]
As of #3738 the client will fail-fast when connecting to a older server version. 

Rather than telling clients to "update their server" we should update the [self hosting doc](https://infrahq.com/docs/reference/self-hosting) with a section about where to download older CLI versions, and provide a link to that in the output error.

**Comment by mchiang0610** [comment]
Should be addressed with this link: 

https://infrahq.com/docs/reference/self-hosting#cli-versions 

This is where we can point users to.
