### ISSUE TITLE
Automatically lookup SSH destination host:port

### ISSUE THREAD

**Issue by dnephin** [infrahq/infra#3757]
Every destination needs at least one `host:port` (or url) to connect to. For the SSH destination we have a few sources that we can use to lookup the IP address, or hostname, and port.

1. `/etc/ssh/sshd_config` ([ref](https://man.openbsd.org/sshd_config#ListenAddress)) may have one or more `ListenAddress` keywords, and one or port `Port` keywords.
2. https://pkg.go.dev/net#Interfaces can give us a list of all the interfaces, and all the addresses for each interface (but no port)
3. if the host happens to be a cloud instance we may be able to use the cloud providers metadata API (`http://169.254.169.254/`) to look up interface addresses, although these should be the same as we get from `net.Interfaces`. This mechanism only works for cloud instances, and we'd have to implement a different lookup for each cloud provider, so I'd like to avoid this option for now.

The `/etc/ssh/sshd_config` is the most reliable, but it may still give us multiple addresses (either because there are multiple `Port` keywords, multiple `ListenAddress` keywords, or maybe `0.0.0.0` is used in `ListenAddress`.
`net.Interfaces` works well as a fallback, but often will give us multiple addresses. We can filter out loopback addresses, but even private IP addresses might be valid if a jump host is used, so we can't exclude much.

It seems like in some cases we may be able to identify a single host:port reliably, but in many cases it will be ambiguous. When it's ambiguous we need the operator installing the connector to specify which address and port should be used. I think we should do this lookup as part of the command that we use to setup the connector. That way we have an opportunity to prompt the user to resolve the ambiguity.

### Manual install using infra CLI

The tentative name for this command is `infra up`.

1. read `/etc/ssh/sshd_config`
2. if there is a single `ListenAddress` (that is not `0.0.0.0`) with a port, or at most one `Port` keyword then use that address
3. if there are no `ListenAddress` keywords, read  `net.Interfaces` to get a list of all the addresses for non-loopback interfaces
4. prompt the user to choose the address they want to use (either from `ListenAddress` or `net.Interfaces), and if there are multiple ports also prompt for which port.
5. write the selection to `/etc/infra/connector.yaml`.

### Automated install

Using something like puppet/chef/ansible/terraform/packer/bash.

1. accept an explicit `address` and `port` (defaults to `22` when not specified)
2. accept an interface name (ex: `eth1`, or `enp1s0`), and use the first address assigned to that interface. That would allow automation to avoid the need to lookup the IP itself, while removing the ambiguity of looking up an address.

**Comment by mxyng** [comment]
This lookup may need to be dynamic since addresses can change, particularly for EC2 or GCE instances

**Comment by dnephin** [comment]
I think if we accepted interface name we could reliably look up the address, because there should be a small number of addresses per interface. I don't think we can reliably look up an address in all cases if we don't have some hints about which one to use.

How common is it for an IP address of a running instance to change? Would it depend on the DHCP lease?

**Comment by mxyng** [comment]
Less often on a running system though it's possible. I'm thinking more along the lines of a restart. The impression I got reading the issue description suggests a one-time configuration which can quickly get out of sync if the address changes

**Comment by mxyng** [comment]
This might be more difficult than expected. The external address may not be available to the SSH host. For example, in GCE, only the internal IP is available when inspecting the network interface. I suspect you'll need to query the metadata service to find the external address

**Comment by dnephin** [comment]
That's good to know! That makes it even more difficult to reliably look up the right enpointAddr without the operator specifying something about how to do that lookup (local lookup vs metadata lookup, or interface name).
