### ISSUE TITLE
Support granting SSH access with group membership

### ISSUE THREAD

**Issue by dnephin** [infrahq/infra#3761]
### Background

The initial technical preview release of the SSH connector only supports granting access directly to a user. A grant where the subject is a group does not work yet (it will not grant access). This limitation exists because we don't have a reasonable API endpoint that the SSH connector can use to get the fully resolved list of users. Today we use `/api/grants?destination=<name>`, which returns us all the grants. The subject of some of those grants may be a group which contains multiple users.

To get notified of all changes that could impact the destination we would need to long-poll on:
1. `ListGrants` by destination
2. `ListGroupMembers` for each group that is a subject in the grants (potentially `n` calls, or it must accept a list of group IDs)

We could implement long polling for `ListUsersByGroup` (`/api/users?group=x`), but that API is not ideal for the connector. It would still need to make `n+1` API calls, which is extra DB connections (see #3586 for why that's an important consideration), and extra work for the client to manage as the group grants change.

Another disadvantage to this approach is that we end up querying and serializing a bunch of data that isn't necessary for the connector. 

We need the `User.SSHLoginName` and `User.ID`, but we don't need any other details about the user, or any of  the timestamps. 

### Proposal

I propose we create a new API endpoint that is designed specifically for the connector use case.

```
GET /api/destinations/:id/users?lastUpdateIndex=<updateIndex>
```

The only request parameters are the `destination.ID` in the path, and the `lastUpdateIndex` for long polling. The response should look something like this:

```go
type response api.ListResponse[api.DestinationUsers]

type DestinationUsers struct {
    User struct {
        ID uid.ID
        SSHLoginName string
    }
    Grants []struct { // a list of these
        Privilege string // always `connect` for SSH (for now), the cluster role for kuberentes
        Resource string // not used for SSH yet, but used as namespace for kubernetes
    }
}
```

This gives us a compact response with all the details we need in the connector.

Some implementation details:
* the query should be something like `SELECT * from grants LEFT JOIN identities ON grants.user_id == identities.id WHERE grants.destination = <destination>` unioned with a similar query for getting all the users in the groups with granted access (need to think more about that query to see if we can avoid the sub-select).
* the implementation of this blocking request is a little more involved than the existing one, because it involves relationships between multiple tables (group membership and grants). We'll need to add notifications for any group membership changes so that we can listen on those changes.
* if we ever support changing the SSHLoginName, this API endpoint gives us a convenient way of being notified of those changes as well. If we use API endpoints that aren't specific to the destination we may have to watch every single user change (which is not great).

**Comment by jmorganca** [comment]
Would we be able to use `GET /api/grants?resource=<destination>&showInherited=true` in this case? That won't solve the extra `User.SSHLoginName` field required, but we could find a way to expose this in the response.

**Comment by dnephin** [comment]
Changes

* [ ] database query
* [ ] api structs / handler
* [ ] blocking request support (notify / listen)


API Test cases

* [ ] user added to group
* [ ] user removed from group
* [ ] grant removed from group
* [ ] grant added to group
* [ ] grant added to user
* [ ] grant removed from user

**Comment by dnephin** [comment]
The first problem that needs to be solved is the subject ID of grants. The subject ID may be either a user ID or group ID. Today we store those ids on the subject field as an encoded string.  Since the ID is not an int, we can't join grants to the user or groups table, and we need that to be able to query the data.

I know of two options to solve this problem:

## Option 1 - `subject_id` and `subject_kind` columns

Replace the `subject` column on the `grants` table with two fields `subject_id` (the ID of either the user or the group) and `subject_kind` (an enum of `user`, `group`).

I believe this approach has a few advantages:
1. it's space efficient - the space required to store these two fields for each `grants` row remains constant even if we add more kinds of subjects, and we only need 64 bits for the ID, and probably only 8 or 16 bits for the kind.
2. it's extensible - if we decide to allow grants that apply to an entire organization, or some other grouping, we don't need a new migration, we can simply add a new value to the `kind` enum.
3. fewer indexes - we suspect we'll only need a single index `(subject_id, subject_kind).
4. the only potential disadvantage I can see is that it's different from our API structure, but I would argue that's normal. We have separate data storage and presentation representations because each of those has different concerns, and we want to allow them to be different.

A join with this approach would look like this:

```sql
SELECT ...
FROM grants
JOIN identities ON grants.subject_kind = 'user' AND grants.subject_id = identities.user_id
...
``` 

## Option 2 - `user_id` and `group_id` columns

Replace the `subject` column on the `grants` table with two fields (`user_id` and `group_id`).

This approach also solves the problem, but is less space efficient (even not with only two kinds of subjets it's 2x 64bit), and would require an alter table if we ever add more. This approach would require two indexes, one on `user_id` and one on `group_id`. We'd have to allow nulls in these columns to avoid doubling the size of these indexes with unnecessary 0 values.

A join with this approach would look like this:

```sql
SELECT ...
FROM grants
JOIN identities ON grants.user_id = identities.id
```


I'm not aware of any significant query performance trade-offs. I would expect both to be about the same since they'll both use an index,  but it's possible one of these approaches allows for better use of the index.

**Comment by dnephin** [comment]
Another problem is how to track the `update_index` for these queries. Today this is easy because our blocking requests only use a single table (`grants`). This new query will need to consider changes to 2 tables: `grants` and `identities_groups`. When we allow `User.SSHLoginName` to be modified we'll also have to include the `identities` table as well.

We track the `update_index` to grants by using the latest value of the `seq_update_index` sequence every time a grant is created or deleted (grants are currently immutable, so no updates). We can use the same `seq_update_index`, but we need to track the value every time a user is added to or removed from a group (`identities_groups`).

## Option 1 - track the user's group membership update_index on the `identities` table

We could add a new column `group_membership_table_index` to the `identities` table. Any time we update a user's group membership (add or remove from any group) we could increment this index. 

The advantage to this approach is that it's an easy change that shouldn't impact any existing queries.

The disadvantage to this approach is that we don't know if the group membership change actually impacted the query. All we know is that some group membership changed, but maybe there were no relevant grants on that grant. We can likely handle these irrelevant updates in the API handler, so it shouldn't be a problem for API consumers.

## Option 2 - track the group membership on `identities_groups`

We could add an `update_index` column to the `identities_groups` table  and update it each time membership changes. The immediate problem with that approach is that currently `identities_groups` rows are hard-deleted, so we'd never see the `update_index` for removing a user from a group. We'd have to change `identities_groups` to be a soft-deleted table, and update all the queries that manage group membership to consider soft-deleted rows.

This approach has the same problems as option 1, group membership changes don't necessarily impact grants to the destination, so we still have to handle unnecessary updates.

This seems like a major change to an already complex relationship with no clear advantages, so I don't think we should use this option.

## Option 3 - a new table to track update_index for relationships

Like option 1, but a separate table for tracking these things. I don't know of any advantages to this approach, but it's a technique I saw used in other systems that implement this style of blocking request.

**Comment by dnephin** [comment]
We also need new `notify` signals sent when group membership changes. Today we do that with database triggers that call a function when any row on the table changes.

We should be able to use the same approach for group membership changes:

```
CREATE TRIGGER group_membership_trigger AFTER INSERT OR DELETE ON identities_groups
FOR EACH ROW EXECUTE FUNCTION group_membership_notify()
```

The `group_membership_notify` function should notify on a channel `group_membership_<org_id>_<group_id>`, since we care about these changes as they apply to groups (specifically the groups that are the subject of grants).
