### ISSUE TITLE
Better default permissions for non-admin users

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#3815]
By default when users are added to an organization today, they receive little to no permissions. Instead, when users are added to an organization, they should receive `view` access (effectively read-only mode) to the organization by default.

**Comment by dnephin** [comment]
What's the use case for giving everyone the `view` role? 

A non-admin user can already see all the destinations (including ones they don't have a grant to access), they can create and manage their own access keys.

Giving them `view` would allow them to see the list of others users in their org, the list of groups (note they can already see their own groups), the list of access keys that are not their own, and the list of grants in their org. 

Do we have some idea of how we expect non-admins to use these?
