### ISSUE TITLE
Re-visit SCIM access keys with 'SCIM' Identity

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#3830]
## Is your feature request related to a problem? Please describe.
Right now access keys are issued directly for providers.

## Describe the solution you'd like
We should look at moving to to 'Provider' identity pattern to match the connector.

**Comment by dnephin** [comment]
The other option is to remove these system-managed users entirely, and use something like #3822 to allow an admin to create keys with fewer privileges. Access key capabilities seem like they might be closer to what users want, and would be easier for us to maintain (fewer special cases).
