### ISSUE TITLE
Timeout when calling `GET /api/grants` with long polling returns an HTML response

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#3841]
When a long polling request times out, the response is sent as an HTML message by any ingress system serving the request. Instead an empty (or error) body with an alternative status code should be used

```
{"level":"error","error":"list grants: <html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n","time":1670545496129,"caller":"connector/connector.go:502","message":"sync grants with kubernetes"}
```

**Comment by dnephin** [comment]
This HTML is coming from nginx, so we'll need to configure nginx to return the right content. Once we have nginx configured with the correct timeout it should be a lot less likely that we see these nginx error pages.

If we do want to customize this response, I believe the docs are here: https://kubernetes.github.io/ingress-nginx/user-guide/custom-errors/

It sounds like we can have an API endpoint that reads these HTTP headers, and returns an appropriate response.
