### ISSUE TITLE
User cannot update their own password using CLI

### ISSUE THREAD

**Issue by mxyng** [infrahq/infra#3882]
Trying to change their own password returns an error `oldPassword is required` but there's no field to enter the old password

```
$ infra info

 Server: infra.infrahq.lvh.me
   User: admin@local (hW3uKifXoG)
 Groups: (none)

```

```
$ infra users edit admin@local --password
  Enter a new password:
? Password: ********
? Confirm Password: ********
Error: validation failed: oldPassword: is required
```

```
$ infra version

 Client: 0.20.0

```

**Comment by dnephin** [comment]
Hmm, I thought I had fixed this in #3653. 

There shouldn't be any need to enter the old password manually, they just entered it. We should be able to get it from the previous request.

**Comment by dnephin** [comment]
I think this is a regression from #3739. `options.Password` only works if the password comes from an env var, not the prompt.

**Comment by mxyng** [comment]
It's a separate problem from the linked issue since this is from explicitly changing the password through `infra user edit` rather than from a login.
