### ISSUE TITLE
Reduce `Server.Config` to only bootstrap config

### ISSUE THREAD

**Issue by dnephin** [infrahq/infra#3915]
## Background

Today we support creating entities and removing entities from the server config file. This is implemented in [loadConfig](https://github.com/infrahq/infra/blob/e1b141ebfa9eced506a9d9304a8607fe22eebdee/internal/server/config.go#L600) , the input struct is [`Server.Config`](https://github.com/infrahq/infra/blob/e1b141ebfa9eced506a9d9304a8607fe22eebdee/internal/server/config.go#L79-L84). We support both creating and removing users, grants, access keys, infra local credentials (username/passwords), and providers.

Now that we have a [terraform provider](https://github.com/infrahq/terraform-provider-infra) most of the use cases we were solving with `loadConfig` are better solved with the terraform provider.

The one use case that can't be solved by the terraform provider is bootstrapping the server. There are two scenarios when bootsrapping is extremely valuable:
* as a "break glass" mechanism for adding an admin or support-admin when an IDP is either unavailable, or has been mis-configured in a way that prevents logins (Ex: someone accidentally deleted the integration from the provider side)
* testing - we frequently need to bootstrap the server in all layers of tests (API handler tests, end-to-end tests, CLI tests, connector tests, etc). We could write something test-only, but that would force us to build something different for break-glass, which is more code to maintain.

## Proposal

Edit: some parts of this proposal were implemented in https://github.com/infrahq/infra/pull/3930

This issue proposes that we reduce `loadConfig` to just the bit we need to satisfy these the bootstraping use case:
* remove `Provider` - that can be setup via the UI or terraform
* remove `Grants` - we only need grants for Infra, there's no use case for bootstrapping destination grants because we can do that from the API.  See below for the replacement to grants.
* remove "delete entity no longer in the config" - bootstrap config only needs to create things, it doesn't need to remove them. This allows us to remove the `CreatedBy` and `NotIDs` query parameters from our list queries, which simplifies the data layer. With this change we no longer have any special requirements on the data layer , we can use the standard options that get used everywhere else
* remove `User.Password` - generally we probably want to be creating short lived access keys for break glass and testing. We don't need to create a password that never expires

With those pieces removed we significant decrease the footprint of this feature. But we also lose a couple things that we need, so this proposal includes the addition of two other small things:

* add `User.Role` (or maybe `User.InfraRole`) - when set to a value this user is given a grant where resource=infra. This allows us to bootstrap admins and support admins
* add `Config.SupportAdminGroups` - this new field would create a grant for each of the groups listed by name. These groups must be in the default organization (like all other bootstrap config). The grant will have resource=infra, and role=support-admin. This gives us an easy way to bootstrap support admins by group  (so that we don't have to manage individual identities). This would allow us to remove granting `support-admin` from the API.

The full boostrap config would look something like this:

```go
type BootstrapConfig struct {
	DefaultOrganizationDomain string
	Users                     []User
	SupportAdminGroups        []string
}

type User struct {
	Name      string
	AccessKey string
	InfraRole string
}

```

**Comment by dnephin** [comment]
While researching this issue I went through to see if my plan would work. I committed those changes to https://github.com/infrahq/infra/compare/dnephin/reduce-server-config. This branch has some failing tests that need to be fixed and doesn't add `SupportAdminGroups`, but otherwise should give us a reasonable idea of the scope of the change.

**Comment by dnephin** [comment]
I guess we should also set a shorter expiry time and inactivity timeout for the access keys. They don't need a 10 year expiry anymore. If this is only for bootstrapping we can make them very short.

**Comment by dnephin** [comment]
> We already have a break glass mechanism for an organizational admin in the form of admin@local created by the Helm chart to bootstrap a single tenan

A cool! Maybe we can delete that code? The code here is more re-usable because the server is not necessarily always going to be deployed via helm, and in testing it's almost never deployed via helm.

> We've found from past experience that using access keys as the primary form of authentication, particularly in a UI environment, is a bad experience for the user. Username and password is a more familiar method.

Don't forget this is not for end users! This is for us as operators. I don't think we need to worry about using the UI, we'd only ever use this with the CLI.

> it seems reasonable to me to configure the same admin@local user with password, login, and either create an access key for extended testing or, if testing the CLI, use the admin's login access key. Since the code paths are different, it might be nice to have both.

The testing requirements are a bit more than just a single org admin. Often we need connector access keys and non-admin users.

**Comment by mxyng** [comment]
To clarify, this is only talking about removing the input to the server config correct? The actual server bootstrap code mostly needs to be untouched since they're needed to create the Infra provider and the connector user.

**Comment by dnephin** [comment]
> The actual server bootstrap code mostly needs to be untouched since they're needed to create the Infra provider and the connector user.

That has not been the case since we added Organizations. Now it's done when the organization is created: https://github.com/infrahq/infra/blob/e1b141ebfa9eced506a9d9304a8607fe22eebdee/internal/server/data/organization.go#L32-L75

**Comment by mxyng** [comment]
For the default organization? If so then great! There's more to cut that I originally expected

**Comment by dnephin** [comment]
Ya, the default organization is also created this way for any new installs: https://github.com/infrahq/infra/blob/e1b141ebfa9eced506a9d9304a8607fe22eebdee/internal/server/data/data.go#L259-L275

We previously had to include it because we were pruning anything that wasn't in the config. But once we remove the "delete not in config" logic it no longer needs to be there.
