### ISSUE TITLE
`POST /api/grants`  and `POST /api/tokens` results in high latency

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#3944]
When making post requests to `/api/grants`, the requests can take anywhere from 3-5s

**Comment by ssoroka** [comment]
As far as I can tell, there are no POST calls taking more than 1s. When I filter on POST (to block out the long-polling GET requests that are supposed to take 5s), there are no log results matching this criteria

**Comment by mxyng** [comment]
Some improvements have been made to the UI which should mitigate this issue. The UI, when creating grants for multiple namespaces, sends a request for each namespace. This can lead to a flood of requests which ironically if is received by the server too slowly will cause a backlog of requests and each request is blocked by the preceding request. 

The improvement is to send a bulk create request so no matter how many namespaces are selected, a single request will be sent.

A second minor improvement focuses on deleting multiple namespace grants. Similar to the earlier improvemnt, this action sends a DELETE request for each selected namespace. Additionally, each DELETE request is followed by a GET to update the UI state. Therefore, the number of requests per selected namespace is actually not 1 but 2 with all of the side effects mentioned earlier. This has been updated to a bulk delete request with a single GET once the bulk delete request has been handled.
