### ISSUE TITLE
Support OAuth Device Flow

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#395]
To support environments where users may not have a browser environment (e.g. a server, or inside a contianer), Infra should support OAuth Device Flow. This would also create a consistent experience if users were to log in via a web browser later on (via a standard OpenID / OAuth flow)

This repo has some great additional information on how GitHub uses it for `gh auth login`: https://github.com/cli/oauth

**Comment by dkulchinsky** [comment]
still relevant I think?

**Comment by jmorganca** [comment]
Fixed in #3446
