### ISSUE TITLE
An error occurred while logging in: unauthorized after connect with company Google workspace

### ISSUE THREAD

**Issue by kittisuw** [infrahq/infra#4293]
After config Connect Provider to Google but show error "An error occurred while logging in: unauthorized" all the time when login.I use this step https://infrahq.com/docs/identity/google.  Pls help How to fix it

![image](https://github.com/infrahq/infra/assets/53901743/21f9a140-2ba1-4a20-90da-36875c2b43af)
---
![image](https://github.com/infrahq/infra/assets/53901743/86ae6860-ae7b-4ff7-a617-b60a3e88348b)
---
![image](https://github.com/infrahq/infra/assets/53901743/5892764b-b5b5-4c98-859e-2ccdc3f64b6d)
<img width="1836" alt="image" src="https://github.com/infrahq/infra/assets/53901743/e5b0275f-e1f4-459c-831c-b8339f6a7020">
---
<img width="1914" alt="image" src="https://github.com/infrahq/infra/assets/53901743/84fa0a43-d2c4-40bb-a5e4-5fb9ca368c68">

**Comment by kittisuw** [comment]
same error integration with Azure AD

**Comment by sanjayprizm** [comment]
same error after integration with Oracle Identity Service
