### ISSUE TITLE
More granular grants

### ISSUE THREAD

**Issue by exolab** [infrahq/infra#4334]
## Is your feature request related to a problem? Please describe.
Granting view permissions to a group does not give them permission to view every type of resource.
Granting view permissions to a group for a namespaces gives them permission to all resources (with the above mentioned constraint) with no further possibility to constrain access

## Describe the solution you'd like
I want to give specific groups more granular permissions, e.g. 
* access custom resource `postgresql` in namespace `databases`
* access custom resource `postgresql` in namespace `databases` by name
* access custom resource `postgresql` in namespace `databases` by label

## Describe alternatives you've considered
Using a different solution than infra

**Comment by JakJung** [comment]
This feature would be very helpful
