### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by igorcoding** [infrahq/infra#4416]
Hi! I really love this project, but it seems like not much activity has been in it throughout 2023. Last new version was released way back in January. Is infra still maintained by anyone or maybe there are some plans for it?
Thank you

**Comment by igorcoding** [comment]
Well, yes, the question is still relevant

**Comment by jsalatiel** [comment]
I'd say it is probably abandoned.

**Comment by pdomineaux** [comment]
Yes, any new on the project maintenance ?
A short answer will be well received even if the answer is no...

**Comment by NumenDivinum** [comment]
Unfortunately it looks abandoned and have some pretty serious bugs preventing from adopting it.

**Comment by romikoops** [comment]
That is a pitty!

**Comment by banschikovde** [comment]
up
