### ISSUE TITLE
cli: Support YAML for `--format` flag

### ISSUE THREAD

**Issue by mxyng** [infrahq/infra#972]
Infra CLI should support at least:

- [x]  `format` flag for current table outputs #2208
- [x] `format=JSON` #2208
- [ ] `format=YAML`

Example, table format with headers:

```
$ infra list --format=text
RESOURCE                   ACCESS          
kubernetes.docker-desktop  cluster-admin   
```

Example, YAML format:

```
$ infra list --format=yaml
resources:
  - resource: kubernetes.docker-desktop
    access: cluster-admin
```

Example, JSON format:

```
$ infra list --format=json
{
  "resources": [
    {
      "resource": "kubernetes.docker-desktop",
      "access": "cluster-admin"
    }
  ]
}
```

Additional fields in YAML and JSON format is probably a good idea

**Comment by kimskimchi** [comment]
https://www.notion.so/infrahq/Verbose-CLI-Outputs-09e8e4de35444b16a74bc09f80c3b07f

**Comment by pdevine** [comment]
The most important things here are:
1. we only need to do JSON for now (other formats aren't super important)
2. this needs to work on more than just one or two commands (i.e. it should work on all commands where it makes sense)
3. this should not just display the results of the API (i.e. don't just display "items": or "count":, etc.)
